
services:
  # MySQL database container
  db:
    image: mysql
    container_name: wizard_shop_db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - online-shop

  # PhpMyAdmin container
  phpmyadmin:
    image: phpmyadmin
    container_name: wizard_shop_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - online-shop

  # Symfony apache project container
  www:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: wizard_shop_php
    volumes:
      - ./:/var/www/html
    restart: always
    ports:
      - "8000:80"
    networks:
      - online-shop

  # Mailer
  mail:
    image: maildev/maildev
    container_name: Maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    environment:
      MAILDEV_SMTP_PORT: 1025
      MAILDEV_WEB_PORT: 1080
    networks:
      - online-shop

#  # Elasticsearch
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.23
#    container_name: wizard_shop_elasticsearch
#    ports:
#      - "9209:9200"
#    environment:
#      - discovery.type=single-node
#      - bootstrap.memory_lock=true
#      - ES_JAVA_OPTS=-Xms1G -Xmx1G
#      - xpack.security.enabled=false
#      - http.cors.enabled=true
#      - http.cors.allow-origin=*
#      - transport.host=localhost
#
#  elasticsearch-head:
#    image: tobias74/elasticsearch-head
#    container_name: wizard_shop_elasticsearch_head
#    depends_on:
#      - elasticsearch
#    ports:
#      - "9109:9100"

networks:
  online-shop:

volumes:
  db-data:
